displays:
  current: home_hdmi-0_dp-4_dvi-d-0.sh
  location: /home/han/.screenlayout
polybar:
  theme: nord
  themes:
  - bars:
    - main
    - left
    - right
    name: nord-arrow
  - bars:
    - main.top.middle
    - left.top.middle
    - right.top.middle
    name: nord
sound:
  port: analog-output-lineout
