displays:
  current: home_dp-4_dvi-d-0-hdmi-0.sh
  location: .screenlayout
i3_wm:
  default_gaps:
    bottom: 10
    left: 10
    right: 10
    top: 10
  settings_file: .config/i3/config
polybar:
  theme: nord-wide
  themes:
  - name: nord-arrow
  - bars:
    - main.top.middle
    - main.top.left
    - main.top.right
    - left.top.middle
    - right.top.middle
    gaps:
      top: 80
    name: nord
  - bars:
    - main.top.middle
    - left.top.middle
    - right.top.middle
    gaps:
      top: 80
    name: nord-wide
  themes_directory: .config/polybar/themes
sound:
  port: analog-output-lineout
