displays:
  current: home_hdmi-0_dp-4_dvi-d-0.sh
  location: /home/han/.screenlayout
list: false
polybar:
  theme: nord-arrow
  themes:
  - name: nord-arrow
  - bars:
    - main.top.middle
    - left.top.middle
    - right.top.middle
    name: nord
  themes_directory: .config/polybar/themes
sound:
  port: analog-output-lineout
