displays:
  current: home_hdmi-0_dp-4_dvi-d-0.sh
  location: /home/han/.screenlayout
polybar:
  theme: nord
  themes:
  - name: nord-arrow
    # bars are optional, if you leave them blank, dot will load all
    # bars found in the theme.
    # bars:
    # - main
    # - left
    # - right
  - bars:
    - main.top.middle
    - left.top.middle
    - right.top.middle
    name: nord
sound:
  port: analog-output-lineout
